### ISSUE TITLE
Updating to a newer version of Java

### ISSUE THREAD

**Issue by TheGloriousDuck** [quickdaffy/quickScript#1]
Assuming you are using Java 8... might be better to move to a more recent version, like 11 or 16

**Comment by quickdaffy** [comment]
Why? So many features are deprecated in those versions that could be useful. The project will stay as java 8.

**Comment by TheGloriousDuck** [comment]
Examples?

**Comment by quickdaffy** [comment]
URLClassLoader comes to mind
Plus, what would I need in that's in java 11 or 16 that I don't have in ajav 8?

**Comment by TheGloriousDuck** [comment]
It might cause incompatibility with someone who is using Java 8+.
Also, I believe URLClassLoader still exists in Java 16, what functionality is removed?

**Comment by quickdaffy** [comment]
If I am going to publish this language, I would be bundling a (possibly modified) JRE with it to exclude compatibility issues.
URLClassLoader doesn't exist in Java 16. Funny story, a kid in my school has a father that works for Oracle's Java division, and when I asked him to ask his father to bring back URLClassLoader, the next day he told me that his father said no.
But yeah, what would be the advantages to using Java 11 or 16?

**Comment by TheGloriousDuck** [comment]
Hm, alright
